[openai]
openai_api_key = "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"
OPENAI_API_KEY = "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"

