[openai]
openai_api_key = "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"
OPENAI_API_KEY = "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"

